// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Session struct {
	ID        int64
	UserID    int64
	SessionID string
	CreatedAt sql.NullString
	ExpiresAt string
}

type User struct {
	ID        int64
	Email     string
	Password  string
	Metadata  interface{}
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}
